
class MyConstants:
    
    GROUP_REQUIREMENT_ANALYST_NAME = 'Requirement Analyst'
    
    REQUIREMENT_DELETED_STATE_ID = '2'
    
    REQUIREMENT_TYPE_CLASSIFICATION_CODE = 'REQ'
    
    BUSINESS_RULE_TYPE_CLASSIFICATION_CODE = 'BR'
    
    TEST_CASE_TYPE_CLASSIFICATION_CODE = 'TC'

    DATATYPE_TYPE_CLASSIFICATION_CODE='DATATP'
    
    PRECONDITION_TYPE_REQUIREMENT = 'REQ'
    
    PRECONDITION_TYPE_DESCRIPTION = 'DES'

    REGISTRATION_TYPE_GOOGLE = "Google"

    REGISTRATION_TYPE_REGULAR = "Regular"
    
    ZERO_HOURS = 'T00:00:00Z'
    
    ZERO = 0