
class MyConstants:
    
    GROUP_REQUIREMENT_ANALYST_NAME = 'Requirement Analyst'
    
    REQUIREMENT_DELETED_STATE_ID = '2'
    
    REQUIREMENT_TYPE_CLASSIFICATION_KEY = 'REQUIREMENT'
    
    TYPE_CLASSIFICATION_CODE = {'REQUIREMENT': "REQ"}
    
    PRECONDITION_TYPE_REQUIREMENT = 'REQ'
    
    PRECONDITION_TYPE_DESCRIPTION = 'DES'